# Generated by Django 6.0.6 on 2026-06-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nacimiento',
            field=models.IntegerField(default=1983),
        ),
    ]
